"""explicit PostgreSQL schema

Revision ID: 20260720_01
Revises:
Create Date: 2026-07-20 16:33:48.709910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260720_01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache_entries',
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cache_key', 'provider')
    )
    op.create_index(op.f('ix_api_cache_entries_expires_at'), 'api_cache_entries', ['expires_at'], unique=False)
    op.create_table('ohlcv_bars',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('bar_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider', 'ticker', 'timeframe', 'bar_time')
    )
    op.create_index('ix_ohlcv_ticker_timeframe_time', 'ohlcv_bars', ['ticker', 'timeframe', 'bar_time'], unique=False)
    op.create_table('provider_rate_limits',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('bucket_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider', 'bucket_date')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=True),
    sa.Column('swing_pace', sa.String(length=64), nullable=True),
    sa.Column('use_case', sa.String(length=64), nullable=True),
    sa.Column('quote', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.JSON(), nullable=True),
    sa.Column('verdict', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('notices', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key')
    )
    op.create_index('ix_analysis_owner_ticker_completed', 'analysis_runs', ['user_id', 'ticker', 'completed_at'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_ticker'), 'paper_trades', ['ticker'], unique=False)
    op.create_index(op.f('ix_paper_trades_user_id'), 'paper_trades', ['user_id'], unique=False)
    op.create_table('swing_watch_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('last_notice_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker')
    )
    op.create_index(op.f('ix_swing_watch_items_user_id'), 'swing_watch_items', ['user_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('trader', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('opened_ts', sa.Float(), nullable=False),
    sa.Column('opened', sa.String(length=64), nullable=False),
    sa.Column('activated_ts', sa.Float(), nullable=True),
    sa.Column('broke_out_ts', sa.Float(), nullable=True),
    sa.Column('entry', sa.Float(), nullable=False),
    sa.Column('stop', sa.Float(), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('trigger_price', sa.Float(), nullable=True),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('close_reason', sa.String(length=64), nullable=True),
    sa.Column('closed_ts', sa.Float(), nullable=True),
    sa.Column('closed', sa.String(length=64), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.Column('pnl_usd', sa.Float(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('cohort_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_cohort_id'), 'trades', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_index(op.f('ix_trades_ticker'), 'trades', ['ticker'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.create_index('uq_trade_active_owner_ticker_trader', 'trades', ['user_id', 'ticker', 'trader'], unique=True, postgresql_where=sa.text("status IN ('open', 'pending')"), sqlite_where=sa.text("status IN ('open', 'pending')"))
    op.create_table('watchlist_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker')
    )
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    op.create_table('analysis_timeframes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('analysis_run_id', sa.String(length=36), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('bias_score', sa.Float(), nullable=False),
    sa.Column('trend_direction', sa.String(length=32), nullable=False),
    sa.Column('last_close', sa.Float(), nullable=True),
    sa.Column('bar_count', sa.Integer(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('levels', sa.JSON(), nullable=False),
    sa.Column('trendlines', sa.JSON(), nullable=False),
    sa.Column('trend_change', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'timeframe')
    )
    op.create_index(op.f('ix_analysis_timeframes_analysis_run_id'), 'analysis_timeframes', ['analysis_run_id'], unique=False)
    op.create_table('trade_indicators',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trade_id', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_indicators_trade_id'), 'trade_indicators', ['trade_id'], unique=False)
    op.create_table('trade_signals',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trade_id', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_signals_trade_id'), 'trade_signals', ['trade_id'], unique=False)
    op.create_table('trade_swing_checks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('trade_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('na', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_swing_checks_trade_id'), 'trade_swing_checks', ['trade_id'], unique=False)
    op.create_table('trade_verdict',
    sa.Column('trade_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_verdict')
    op.drop_index(op.f('ix_trade_swing_checks_trade_id'), table_name='trade_swing_checks')
    op.drop_table('trade_swing_checks')
    op.drop_index(op.f('ix_trade_signals_trade_id'), table_name='trade_signals')
    op.drop_table('trade_signals')
    op.drop_index(op.f('ix_trade_indicators_trade_id'), table_name='trade_indicators')
    op.drop_table('trade_indicators')
    op.drop_index(op.f('ix_analysis_timeframes_analysis_run_id'), table_name='analysis_timeframes')
    op.drop_table('analysis_timeframes')
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index('uq_trade_active_owner_ticker_trader', table_name='trades', postgresql_where=sa.text("status IN ('open', 'pending')"), sqlite_where=sa.text("status IN ('open', 'pending')"))
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_ticker'), table_name='trades')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_cohort_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_swing_watch_items_user_id'), table_name='swing_watch_items')
    op.drop_table('swing_watch_items')
    op.drop_index(op.f('ix_paper_trades_user_id'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_ticker'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index('ix_analysis_owner_ticker_completed', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('provider_rate_limits')
    op.drop_index('ix_ohlcv_ticker_timeframe_time', table_name='ohlcv_bars')
    op.drop_table('ohlcv_bars')
    op.drop_index(op.f('ix_api_cache_entries_expires_at'), table_name='api_cache_entries')
    op.drop_table('api_cache_entries')
    # ### end Alembic commands ###
